In [1]:
import torch
import torch.nn as nn

In [2]:
data = None
data

In [3]:
softmax_function = None
output = None
output

## **Exercise 1, 2**

In [6]:
x = torch.tensor([5.0, 3.0])

output = torch.sigmoid(x)
print(output)

tensor([0.9933, 0.9526])


In [7]:
import torch.nn as nn

class MySigmoid(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return 1 / (1 + torch.exp(-x))

# Create an instance of the custom sigmoid class
data = torch.Tensor([3.0, -2.0])
my_sigmoid = MySigmoid()
output = my_sigmoid(data)
output

tensor([0.9526, 0.1192])

In [8]:
# input data
x = torch.tensor([1, 5, -4, 3, -2])

# sigmoid function
output = my_sigmoid(x)
print(output)

tensor([0.7311, 0.9933, 0.0180, 0.9526, 0.1192])


## **Exercise 3, 4, 5**

In [19]:
from abc import ABC, abstractmethod

class Person(ABC):
    def __init__(self, name:str, yob:int):
        self._name = name
        self._yob = yob

    def get_yob(self):
        return self._yob

    @abstractmethod
    def describe(self):
        pass


class Student(Person):
    def __init__(self, name:str, yob:int, grade:str):
        super().__init__(name, yob)
        self._grade = grade
    
    def describe(self):
        return f"Student - Name: {self._name} - YoB: {self._yob} - Grade {self._grade}"


class Teacher(Person):
    def __init__(self, name:str, yob:int, subject:str):
        super().__init__(name, yob)
        self._subject = subject
    
    def describe(self):
        return f"Teacher - Name: {self._name} - YoB: {self._yob} - Subject: {self._subject}"

class Doctor(Person):
    def __init__(self, name:str, yob:int, specialist:str):
        super().__init__(name, yob)
        self._specialist = specialist
    
    def describe(self):
        return f"Doctor - Name: {self._name} - YoB: {self._yob} - Specialist: {self._specialist}"

In [20]:
student1 = Student(name="studentZ2023", yob=2011, grade="6")
student1.describe()

teacher1 = Teacher(name="teacherZ2023", yob=1991, subject="History")
teacher1.describe()

doctor1 = Doctor(name="doctorZ2023", yob=1981, specialist="Endocrinologists")
doctor1.describe()

'Doctor - Name: doctorZ2023 - YoB: 1981 - Specialist: Endocrinologists'

## **Exercise 6**

In [29]:
class Ward:
    def __init__(self, name:str):
        self.__name = name
        self.__list_people = list()

    def add_person(self, person:Person):
        self.__list_people.append(person)

    def describe(self):
        print(f'Ward name: {self.__name}')
        for person in self.__list_people:
            print(person.describe())

    def count_doctor(self):
        count = 0
        for person in self.__list_people:
            if isinstance(person, Doctor):
                count += 1
        return count

    def sort_age(self):
        self.__list_people.sort(key=lambda x: x.get_yob())

    def compute_average(self):
        teacher_yobs = []
        for person in self.__list_people:
            if isinstance(person, Teacher):
                teacher_yobs.append(2025 - person.get_yob())
        return sum(teacher_yobs) / len(teacher_yobs)

In [30]:
student1 = Student(name="studentA", yob=2010, grade="7")
student1.describe()

teacher1 = Teacher(name="teacherA", yob=1969, subject="Math")
teacher1.describe()

doctor1 = Doctor(name="doctorA", yob=1945, specialist="Endocrinologists")
doctor1.describe()


print()
teacher2 = Teacher(name="teacherB", yob=1995, subject="History")
doctor2 = Doctor(name="doctorB", yob=1975, specialist="Cardiologists")
ward1 = Ward(name="Ward1")
ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)
ward1.add_person(doctor2)
ward1.describe()

# 2(c)
print(f"\nNumber of doctors: {ward1.count_doctor()}")

# 2(d)
print("\nAfter sorting Age of Ward1 people")
ward1.sort_age()
ward1.describe()

# 2(e)
print(f"\nAverage year of birth (teachers): {ward1.compute_average()}")


Ward name: Ward1
Student - Name: studentA - YoB: 2010 - Grade 7
Teacher - Name: teacherA - YoB: 1969 - Subject: Math
Teacher - Name: teacherB - YoB: 1995 - Subject: History
Doctor - Name: doctorA - YoB: 1945 - Specialist: Endocrinologists
Doctor - Name: doctorB - YoB: 1975 - Specialist: Cardiologists

Number of doctors: 2

After sorting Age of Ward1 people
Ward name: Ward1
Doctor - Name: doctorA - YoB: 1945 - Specialist: Endocrinologists
Teacher - Name: teacherA - YoB: 1969 - Subject: Math
Doctor - Name: doctorB - YoB: 1975 - Specialist: Cardiologists
Teacher - Name: teacherB - YoB: 1995 - Subject: History
Student - Name: studentA - YoB: 2010 - Grade 7

Average year of birth (teachers): 43.0


## **Exercise 7, 8**

In [31]:
class MyStack:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__stack = []

    def is_empty(self):
        return len(self.__stack) == 0

    def is_full(self):
        return len(self.__stack) == self.__capacity

    def pop(self):
        if self.is_empty():
            print("Stack is empty!")
            return None
        return self.__stack.pop()

    def push(self, value):
        if self.is_full():
            print("Stack is full!")
            return 
        self.__stack.append(value)

    def top(self):
        if self.is_empty():
            print("Stack is empty!")
            return None
        return self.__stack[-1]

In [32]:
stack1 = MyStack(capacity=5)

stack1.push(1)

stack1.push(2)

print(stack1.is_full())

print(stack1.top())

print(stack1.pop())

print(stack1.top())

print(stack1.pop())

print(stack1.is_empty())

False
2
2
1
1
True


In [33]:
stack2 = MyStack(capacity=2)

stack2.push(1)

stack2.push(2)

print(stack2.top())

print(stack2.is_full())

print(stack2.pop())

print(stack2.pop())

print(stack2.is_empty())

print(stack2.pop())

2
True
2
1
True
Stack is empty!
None


## **Exercise 9, 10**

In [34]:
class MyQueue:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__queue = []

    def is_empty(self):
        return len(self.__queue) == 0

    def is_full(self):
        return len(self.__queue) == self.__capacity

    def dequeue(self):
        if self.is_empty():
            print("Queue is empty!")
            return None
        return self.__queue.pop(0)

    def enqueue(self, value):
        if self.is_full():
            print("Queue is full!")
            return 
        self.__queue.append(value)

    def front(self):
        if self.is_empty():
            print("Queue is empty!")
            return None
        return self.__queue[0]

In [35]:
queue1 = MyQueue(capacity=5)

queue1.enqueue(1)

queue1.enqueue(2)

print(queue1.is_full())

print(queue1.front())

print(queue1.dequeue())

print(queue1.front())

print(queue1.dequeue())

print(queue1.is_empty())

False
1
1
2
2
True


In [36]:
queue2 =  MyQueue(capacity=2)

queue2.enqueue(1)

queue2.enqueue(2)

print(queue2.front())

print(queue2.is_full())

print(queue2.dequeue())

print(queue2.dequeue())

print(queue2.is_empty())

1
True
1
2
True


In [ ]:
queue1 = MyQueue(capacity=2)

queue1.enqueue(1)

queue1.enqueue(2)

queue1.enqueue(2)